---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - stack_install_root_dir is defined
      - stack_version is defined
      - stack_name is defined
      - services_to_run is defined

- name: Set the services that are running on a host to {{ services_to_run }}
  command: "{{ stack_install_root_dir }}/{{ stack_name }}/{{ stack_name }}-{{ stack_version }}/set_services.sh -m {{ services_to_run }}"
